version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-local
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
        - ./data:/data
    command: server /data --console-address ":9001"

  init:
    image: alpine:latest
    depends_on:
      - minio
    volumes:
      - ./init:/init
      - ./srcdatafiles:/srcdata
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "sleep 10 && chmod +x /init/mc /init/init.sh && /init/init.sh"
